# Generated by Django 6.0.5 on 2026-05-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('years_experience', models.IntegerField(default=10)),
                ('company_history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('survey_type', models.CharField(max_length=150)),
                ('property_location', models.TextField()),
                ('survey_date', models.DateField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STAT', 'Statistic'), ('TIMELINE', 'Timeline Event'), ('PROJECT', 'Completed Project')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, help_text="e.g. '500+' or '2023'", max_length=100, null=True)),
                ('description', models.TextField()),
                ('year', models.IntegerField(blank=True, help_text='Required for Timeline Events', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image_url', models.CharField(blank=True, help_text='Fallback URL or absolute asset link', max_length=500, null=True)),
                ('category', models.CharField(default='General', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Short summary for service card')),
                ('detail_text', models.TextField(help_text='Detailed description of the service')),
                ('process', models.TextField(help_text='Survey process, semicolon or newline separated')),
                ('benefits', models.TextField(help_text='Benefits of the service, semicolon or newline separated')),
                ('equipment', models.CharField(help_text='Equipment used, comma separated', max_length=300)),
                ('image_url', models.CharField(help_text='Path/URL to service illustration or photo', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('page_visited', models.CharField(default='Home', max_length=200)),
            ],
        ),
    ]
