# Generated by Django 6.0.5 on 2026-06-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, default='Property Owner', max_length=200, null=True)),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Deccan Digital Surveys', max_length=250)),
                ('hero_subtitle', models.TextField(default='Professional Land Surveying Services across India')),
                ('hero_primary_btn', models.CharField(default='Book Survey', max_length=100)),
                ('hero_secondary_btn', models.CharField(default='Contact Us', max_length=100)),
                ('about_description', models.TextField(default='Deccan Digital Surveys was founded with a vision to revolutionize the land measurement practices in India...')),
                ('about_mission', models.TextField(default='To deliver exceptionally precise, reliable, and technology-driven surveying solutions...')),
                ('about_vision', models.TextField(default='To be the premier digital surveying agency in India...')),
                ('stat_experience_years', models.IntegerField(default=8)),
                ('stat_projects_completed', models.CharField(default='1,200+', max_length=50)),
                ('stat_clients_served', models.CharField(default='950+', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='coordinates',
            field=models.CharField(blank=True, help_text='Format: lat,lng', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='land_document',
            field=models.FileField(blank=True, null=True, upload_to='bookings/documents/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='location_sketch',
            field=models.ImageField(blank=True, null=True, upload_to='bookings/sketches/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='bookings/images/'),
        ),
        migrations.AddField(
            model_name='servicecontent',
            name='equipment_details',
            field=models.TextField(blank=True, help_text='Detailed equipment used info', null=True),
        ),
        migrations.AddField(
            model_name='servicecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='servicecontent',
            name='sample_photos_json',
            field=models.TextField(blank=True, help_text='Extra sample photos in JSON array format', null=True),
        ),
        migrations.AddField(
            model_name='servicecontent',
            name='technical_specifications',
            field=models.TextField(blank=True, help_text='Full technical specifications', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicecontent',
            name='image_url',
            field=models.CharField(blank=True, help_text='Fallback URL or absolute asset link', max_length=500, null=True),
        ),
    ]
