# Generated by Django 6.0.5 on 2026-06-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teammember_testimonial_uploadedfile_websitesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='hero_image_url',
            field=models.CharField(blank=True, default='/images/hero_bg.png', max_length=500, null=True),
        ),
    ]
