# Generated by Django 6.0.5 on 2026-06-18 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_websitesettings_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_surveyor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.teammember'),
        ),
    ]
