# Generated by Django 6.0.5 on 2026-06-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking_assigned_surveyor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recommended_service', models.CharField(blank=True, max_length=200, null=True)),
                ('is_converted', models.BooleanField(default=False)),
            ],
        ),
    ]
